name: Python Project CI

on: [push]

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python (3.12)
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run tests
        run: pytest

  my_second_job:
    needs: my_first_job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python (3.13)
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install dependencies (3.13)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run tests (3.13)
        run: pytest